:github-address: https://github.com/hazelcast-guides/terraform-quickstarts

:templates-url: https://raw.githubusercontent.com/hazelcast-guides/adoc-templates/master

// Use this relative url if you are going to publish the guide on the guides site.
// Note that this url will not work locally and raise asciidoctor errors.
// So, complete the guide with the above url and set the below one just before 
// publishing on the guides site.
//
//:templates-url: templates:ROOT:page$/

= Use Hazelcast with OpenFaaS

This guide will get you started with using Hazelcast Clients in OpenFaaS functions for connecting to Hazelcast clusters on Kubernetes.

include::{templates-url}/link-to-repo.adoc[]

== What You Will Learn

With the popularity of Function as a Service (FaaS) rising, Kubernetes was also brought into it. OpenFaaS is one of the projects that allows you to deploy serverless functions onto Kubernetes.

Serverless functions were designed to be stateless, however this slows down the functions for some use cases, generally connection set-up time holds a considerable portion of the response time. OpenFaaS with the use of `of-watchdog`, partially solves this problem by allowing functions to be able to hold their states between calls. This approach helps Hazelcast because now the clients in the functions can persist their connection with the cluster between function calls, thus allowing faster response times.

In the guide, we will deploy OpenFaaS onto Kubernetes. We will also create a Hazelcast cluster and deploy OpenFaaS functions with Hazelcast Clients in them. We will use Java, Python and Nodejs clients and we will compare the response times of functions created with `of-watchdog` and `Classical Watchdog`.

== Prerequisites

- A running Kubernetes cluster, for example https://v1-18.docs.kubernetes.io/docs/tasks/tools/install-minikube/[minikube]

- Kubernetes commandline tool, https://v1-18.docs.kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl]

- https://helm.sh/docs/intro/install/[Helm CLI]

- https://docs.openfaas.com/cli/install/[OpenFaaS command line tool]

- https://docs.docker.com/engine/install/[Docker installed]

- https://github.com/rakyll/hey#installation[hey] (optional)


== Install and Configure OpenFaaS on Kubernetes

In this guide we are going to use Minikube as the Kubernetes environment.

We are going to install OpenFaaS on Minikube using Helm CLI. We start by adding two namespaces `openfaas` and `openfaas-fn`. If you want to use different namespaces edit the following file used in the command below.

[bash]
```
kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
```

Now, add OpenFaaS to the Helm chart.

[bash]
```
helm repo add openfaas https://openfaas.github.io/faas-netes/
```

You can expose the OpenFaaS gateway with different resources. Update the `helm upgrade` command with your choice . 

- NodePort, (default) pass no additional flags
- LoadBalancer, add --set serviceType=LoadBalancer
- IngressController, add --set ingress.enabled=true

When NodePort is used you can access the gateway by using `kubectl port-forward`. In this guide, we are going to use NodePort.

Now deploy OpenFaaS onto Kubernetes.

[bash]
```
helm repo update \
&& helm upgrade openfaas --install openfaas/openfaas \
--namespace openfaas  \
--set functionNamespace=openfaas-fn \
--set generateBasicAuth=true
```

=== Log-in to OpenFaaS

Wait for gateway to be ready.

[bash]
```
kubectl rollout status -n openfaas deploy/gateway
```

Run the following command to create a tunnel between Kubernetes cluster and your local computer. You may run this in a seperate terminal.

[bash]
```
kubectl port-forward svc/gateway -n openfaas 8080:8080
```

Now, we can access the gateway from `http://127.0.0.1:8080`.

If you're using a managed cloud Kubernetes service then get the LoadBalancer's IP address or DNS entry from the EXTERNAL-IP field from the command below.

[bash]
```
kubectl get svc -o wide gateway-external -n openfaas
```

Your URL will be the IP or DNS entry above on port 8080.

You can log in to Gateway with following commands.

[bash]
```
export OPENFAAS_URL="http://127.0.0.1:8080" # Change if you are using a managed cloud Kubernetes service.

# This command retrieves your password
PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)

# This command logs in and saves a file to ~/.openfaas/config.yml
echo -n $PASSWORD | faas-cli login --username admin --password-stdin
```

You can also see and call your functions from a browser. Go to your `$OPENFAAS_URL` and provide username and password as `admin` and `$PASSWORD`.

== Deploy Hazelcast Cluster onto Kubernetes 

We will deploy Hazelcast cluster using Helm. This will deploy the Helm chart on whatever namespace you run it.

[bash]
```
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install hz-hazelcast hazelcast/hazelcast
```
== Create Function with Hazelcast Client

OpenFaaS CLI provides function templates for different runtime environments and watch-dogs. We are going to implement the functions in Java, Python and NodeJs. We will be using both `of-watchdog` and `Classic Watchdog`. By using `of-watchdog` we can preserve the database connections, so our clients do not need to connect to the cluster after each function call. You can find more information on watchdogs (here)[https://docs.openfaas.com/architecture/watchdog/].

Clone the repository from {templates-url}[here] and `cd` into the repository

[tabs]
====
Java::
+
--
You can either use completed functions under the `hz-client-java` folder, or you can build your functions using templates and `faas-cli`. 

If you choose to use completed functions, `cd` into `hz-client-java/of-watchdog`. You need to change `image` part in `hz-client-java-ofwatchdog.yml` to your Docker Hub username.

NOTE: If you are not using a local Kubernetes cluster, you will also need to change the `gateway` section in `hz-client-java-ofwatchdog.yml` with the value of `OPENFAAS_URL` environment variable you created before.

After the change you can build, push and deploy your functions using the following command.
```
faas-cli up -f hz-client-java-ofwatchdog.yml  
```

If you choose to create your function using templates, run the following commands. You can choose to run these commands in a newly created directory.
[bash]
```
# Pulls the templates for different runtimes, watchdogs for these templates can be found at https://github.com/openfaas/templates#classic-templates
faas-cli template pull 

# Create a new java11 function named hz-client-java-ofwatchdog , Docker Hub prefix will be your username
faas-cli new --lang java11 hz-client-java-ofwatchdog --prefix="YOUR_DOCKER_HUB_USERNAME"
```

Your template is now created. Copy the contents of `functions/java-handler.java` into `hz-client-java-ofwatchdog/src/.../Handler.java'.

NOTE: If you deployed your Hazelcast cluster in a different namespace other than `default` do not forget to change the `default` in `cluster_members` to your namespace in the file `hz-client-java-ofwatchdog/src/.../Handler.java'.


Add following to `dependencies` section in `hz-client-java-ofwatchdog/build.gradle`
[gradle]
```
    compile 'com.hazelcast:hazelcast-all:4.2'
```

Now you can build, push and deploy your functions using the following command.

```
faas-cli up -f hz-client-java-ofwatchdog.yml  
```


--

Python::
+
--
You can either use completed functions under the `hz-client-python` folder or you can build your functions using templates and `faas-cli`. 

If you choose to use completed functions, cd into `hz-client-python/of-watchdog`. You need to change `image` part in `hz-client-python-ofwatchdog.yml` to your Docker Hub username

NOTE: If you are not using a local Kubernetes cluster, you will also need to change the `gateway` section in `hz-client-python-ofwatchdog.yml` with the value of `OPENFAAS_URL` environment variable you created before.

After the change you can build, push and deploy your functions by the following command.

```
faas template pull https://github.com/openfaas-incubator/python-flask-template #Needed for building the image from template
faas-cli up -f  hz-client-python-ofwatchdog.yml  --build-arg "TEST_ENABLED=false"
```

If you choose to create your function using templates, run the following commands. You can choose to run these commands in a newly created directory.
[bash]
```
# Pulls the templates that has python3 flask with ofwatchdog, you can learn more about watchdogs here https://github.com/openfaas/templates#classic-templates
faas template pull https://github.com/openfaas-incubator/python-flask-template

# Create a new python3-flask function named hz-client-python-ofwatchdog, Docker Hub prefix will be your username
faas-cli new --lang python3-flask hz-client-python-ofwatchdog --prefix="YOUR_DOCKER_HUB_USERNAME"
```

Your template is now created. Copy the contents of `functions/python-handler.py` into 'hz-client-python-ofwatchdog/handler.py'.

NOTE: If you deployed your Hazelcast cluster in a different namespace other than `default` do not forget to change the `default` in `cluster_members` to your namespace in the file 'hz-client-python-ofwatchdog/handler.py'.

Add the following to `hz-client-python-ofwatchdog/requirements.txt`

```
hazelcast-python-client
```

Now you can build, push and deploy your functions by the following command.

```
faas template pull https://github.com/openfaas-incubator/python-flask-template
faas-cli up -f  hz-client-python-ofwatchdog.yml  --build-arg "TEST_ENABLED=false"
```
--

Nodejs::
+
--
You can either use completed functions under the `hz-client-node` folder, or you can build your functions using `faas-cli` and templates. 

If you choose to use completed functions, cd into `hz-client-node/of-watchdog`. You need to change `image` part in `hz-client-node-ofwatchdog.yml` to your Docker Hub username.

NOTE: If you are not using a local Kubernetes cluster, you will also need to change the `gateway` section in `hz-client-node-ofwatchdog.yml` with the value of `OPENFAAS_URL` environment variable you created before.

After the change you can build, push and deploy your functions by the following command.
```
faas-cli up -f hz-client-node-ofwatchdog.yml
```

If you choose to create your function using templates, run the following commands. You can choose to run these commands in a newly created directory.
[bash]
```
# Pulls the templates for different runtimes, watchdogs for these templates can be found at https://github.com/openfaas/templates#classic-templates
faas-cli template pull 

# Create a new node14 function named hz-client-node-ofwatchdog.yml, Docker Hub prefix will be your username
faas-cli new --lang node14 hz-client-node-ofwatchdog.yml --prefix="YOUR_DOCKER_HUB_USERNAME"
```

Your template is now created. Copy the contents on `functions/node-handler.js` into 'hz-client-node-ofwatchdog/handler.js'.

NOTE: If you deployed your Hazelcast cluster in a different namespace other than `default` do not forget to change the `default` in `cluster_members` to your namespace in the file 'hz-client-node-ofwatchdog/handler.js'.

Add following to `dependencies` section in `hz-client-node-ofwatchdog/package.json`
```
"hazelcast-client": "^4.1.0"
```

Now you can build, push and deploy your functions by the following command.

```
faas-cli up -f hz-node-client-ofwatchdog.yml  
```

--
====

== Trigger Functions 

Every deployed function will have http triggers at `<gateway_address>/function/<function-name>`. 

After deploying the functions using `faas-cli up` or `faas-cli deploy`, you may choose invoke them by using curl, `faas-cli invoke` or the browser. We are going to use https://github.com/rakyll/hey[hey] project to invoke the functions.

[tabs]
====
Java::
+
--
You can call the function with the following command.

```
hey -n 100 -c 4 ${OPENFAAS_URL}/function/hz-client-java-ofwatchdog
```

This will invoke the function 100 times using 4 concurrent workers.
--
Python::
+
--
You can call the function with the following command.

```
hey -n 100 -c 4 ${OPENFAAS_URL}/function/hz-client-python-ofwatchdog
```

This will invoke the function 100 times using 4 concurrent workers.
--
Nodejs::
+
--
You can call the function with the following command.

```
hey -n 100 -c 4 ${OPENFAAS_URL}/function/hz-client-node-ofwatchdog
```

This will invoke the function 100 times using 4 concurrent workers.
--
====

The watchdogs used in these functions allowed us to use the same Hazelcast Client connecting to the cluster. We can also see the difference in time by deploying the same functions with the `Classic Watchdog`. 

Java does not have templates with `Classical Watchdog`. So the next section will only available for `Python` and `Nodejs`.

[tabs]
====
Python::
+
--
Change the `image` section in `hz-client-python/classic-watchdog/hz-client-python-classic.yml`.

NOTE: If you are not using a local Kubernetes cluster, you will also need to change the `gateway` section in `hz-client-java-classic.yml` with the value of `OPENFAAS_URL` environment variable you created before.

NOTE: If you deployed your Hazelcast cluster in a different namespace other than `default` do not forget to change the `default` in `cluster_members` to your namespace in the file `hz-client-python-classic/handler.py`.

Now, you can deploy the function with the following command.

```
faas-cli up -f hz-client-python-classic.yml
```

We are going to call the functions as follows:

```
hey -n 100 -c 4 ${OPENFAAS_URL}/function/hz-client-python-classic
```

This will invoke the function 100 times using 4 concurrent workers.
--
Nodejs::
+
--
Change the `image` section in `hz-client-node/classic-watchdog/hz-client-node-classic.yml`.

NOTE: If you are not using a local Kubernetes cluster, you will also need to change the `gateway` section in `hz-client-java-classic.yml` with the value of `OPENFAAS_URL` environment variable you created before.

NOTE: If you deployed your Hazelcast cluster in a different namespace other than `default` do not forget to change the `default` in `cluster_members` to your namespace in the file `hz-client-node-classic/handler.js`.

Now, you can deploy the function with the following command.

```
faas-cli up -f hz-client-node-classic.yml
```

We are going to call the functions as follows:

```
hey -n 100 -c 4 ${OPENFAAS_URL}/function/hz-client-node-classic
```

This will invoke the function 100 times using 4 concurrent workers.
--
====

Comparing the two deployed versions for `of-watchdog` and `Classic Watchdog`, you should see dramatic results between response times.Because `of-watchdog` allows clients to persist their connection, it will be considerably faster.

== Summary

In this guide we deployed OpenFaaS on Kubernetes then we created a Hazelcast cluster for our Hazelcast clients in functions. We first used `of-watchdog` as the watchdog for our functions. After seeing the results of `of-watchdog`, we deployed our functions with `Classic Watchdog`. Comparing these two we stated using `of-watchdog` with Hazelcast Clients is by far the better option.

== See Also

- xref:kubernetes:ROOT:index.adoc[Deploy Hazelcast Cluster on Kubernetes]

- xref:kubernetes-ssl:ROOT:index.adoc[Enable SSL between Hazelcast Members and Clients on Kubernetes]
